name: Raspberry builder 

on:
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Deply torrserve to PBR
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker build
        run: docker build . -t torrserve:latest
      
      - name: Docker rm
        run: docker rm --force /torrserve || true
        
      - name: Docker run
        run: docker run --name torrserve -d --restart=unless-stopped -p 8090:8090 torrserve:latest
        
      #- name: Docker build action step
      #  uses: docker/build-push-action@v2
      #  with:
      #    tags: torrserve:latest
      #    push: false
      #- name: Docker run
      #  uses: ./
      #  with:
      #    image: torrserve:latest
      #    run: echo "hello world"
      #    options: -d --restart=unless-stopped
